/**
 * @file main.h
 * @brief Main Application Header - Flight Computer
 * @author Zenith Rocket Team
 * @date 2025
 * 
 * STM32F429ZIT6 Flight Computer for IREC 2026
 * 
 * Pin Assignments (Example - adjust to your PCB):
 * 
 * IMU 1 (MPU9250):      I2C1 (PB6-SCL, PB7-SDA)
 * IMU 2 (BNO055):       I2C2 (PB10-SCL, PB11-SDA)
 * Baro 1 (BMP380):      I2C1 (shared with MPU9250)
 * Baro 2 (MS5611):      SPI2 (PB13-SCK, PB14-MISO, PB15-MOSI, PB12-CS)
 * GPS (NEO-7M):         UART2 (PA2-TX, PA3-RX)
 * LoRa (E32-433T30D):   UART3 (PB10-TX, PB11-RX), M0=PC0, M1=PC1, AUX=PC2
 * Flash (W25Q40):       SPI1 (PA5-SCK, PA6-MISO, PA7-MOSI, PA4-CS)
 * Pyro 1 (Drogue):      PE0 (Fire), PE1 (Continuity ADC/Digital)
 * Pyro 2 (Main):        PE2 (Fire), PE3 (Continuity ADC/Digital)
 * Arm Switch:           PE4 (Active low with pull-up)
 * Buzzer:               PE5 (PWM via TIM9)
 * LED Status:           PE6 (General status)
 * Battery ADC:          PA0 (ADC1_IN0)
 */

#ifndef MAIN_H
#define MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f4xx_hal.h"

/*============================================================================
 * PERIPHERAL HANDLES (defined in main.c, generated by CubeMX)
 *============================================================================*/

extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;
extern SPI_HandleTypeDef hspi1;
extern SPI_HandleTypeDef hspi2;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart3;
extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim9;

/*============================================================================
 * PIN DEFINITIONS
 *============================================================================*/

/* Pyro Channels */
#define PYRO1_FIRE_PIN          GPIO_PIN_0
#define PYRO1_FIRE_PORT         GPIOE
#define PYRO1_CONT_PIN          GPIO_PIN_1
#define PYRO1_CONT_PORT         GPIOE

#define PYRO2_FIRE_PIN          GPIO_PIN_2
#define PYRO2_FIRE_PORT         GPIOE
#define PYRO2_CONT_PIN          GPIO_PIN_3
#define PYRO2_CONT_PORT         GPIOE

/* Arm Switch */
#define ARM_SWITCH_PIN          GPIO_PIN_4
#define ARM_SWITCH_PORT         GPIOE

/* Buzzer */
#define BUZZER_PIN              GPIO_PIN_5
#define BUZZER_PORT             GPIOE

/* Status LED */
#define LED_STATUS_PIN          GPIO_PIN_6
#define LED_STATUS_PORT         GPIOE

/* SPI Chip Selects */
#define FLASH_CS_PIN            GPIO_PIN_4
#define FLASH_CS_PORT           GPIOA

#define MS5611_CS_PIN           GPIO_PIN_12
#define MS5611_CS_PORT          GPIOB

/* LoRa Control */
#define LORA_M0_PIN             GPIO_PIN_0
#define LORA_M0_PORT            GPIOC
#define LORA_M1_PIN             GPIO_PIN_1
#define LORA_M1_PORT            GPIOC
#define LORA_AUX_PIN            GPIO_PIN_2
#define LORA_AUX_PORT           GPIOC

/*============================================================================
 * TIMING CONFIGURATION
 *============================================================================*/

#define LOOP_RATE_HZ            100     /* Main loop rate */
#define LOOP_PERIOD_MS          (1000 / LOOP_RATE_HZ)

#define SENSOR_RATE_HZ          100     /* Sensor sampling rate */
#define GPS_RATE_HZ             1       /* GPS update rate */
#define TELEMETRY_RATE_HZ       10      /* Telemetry transmission rate */
#define LOG_RATE_HZ             50      /* Data logging rate */

/*============================================================================
 * SYSTEM STATES
 *============================================================================*/

typedef enum {
    SYS_STATE_INIT,
    SYS_STATE_SELF_TEST,
    SYS_STATE_IDLE,
    SYS_STATE_ARMED,
    SYS_STATE_FLIGHT,
    SYS_STATE_RECOVERY,
    SYS_STATE_ERROR
} SystemState_t;

/*============================================================================
 * FUNCTION PROTOTYPES
 *============================================================================*/

void SystemClock_Config(void);
void Error_Handler(void);

#ifdef __cplusplus
}
#endif

#endif /* MAIN_H */
